### ISSUE TITLE
BERTMap fails with transformers>=5.0; works with transformers==4.37.2 and accelerate==0.21.0

### ISSUE THREAD

**Issue by akikuno** [KRR-Oxford/DeepOnto#32]
### Description

The current version of `deeponto` fails to run the BERTMap pipeline when using `transformers>=5.0`. Specifically, the following error is raised during initialization:

```
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy'
```

This error stems from API changes introduced in `transformers 5.x`, which affect the way `TrainingArguments` and `Trainer` behave.

---

### 🔁 Steps to Reproduce

```bash
# Create a new environment
conda create -y -n test_beatmap python=3.10 openjdk
conda activate test_beatmap

wget http://purl.obolibrary.org/obo/mp.owl
wget http://www.ebi.ac.uk/efo/efo.owl
wget https://github.com/KRR-Oxford/DeepOnto/blob/main/src/deeponto/align/bertmap/default_config.yaml

pip install transformers torch rdflib scikit-learn
pip install git+https://github.com/KRR-Oxford/DeepOnto.git
```

```python
from deeponto.onto import Ontology
from deeponto.align.bertmap import BERTMapPipeline

config_file = "default_config.yaml"
src_onto_file = "mp.owl"  
tgt_onto_file = "efo.owl" 

config = BERTMapPipeline.load_bertmap_config(config_file)
src_onto = Ontology(src_onto_file)
tgt_onto = Ontology(tgt_onto_file)

bertmap = BERTMapPipeline(src_onto, tgt_onto, config)
```

---

### 💥 Error Output (transformers >=5.0)

```
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy'
```

---

### ✅ Working Configuration

Downgrading `transformers` to 4.37.2 and using `accelerate==0.21.0` resolves the issue:

```bash
pip install "transformers==4.37.2" "accelerate==0.21.0" torch rdflib scikit-learn
pip install git+https://github.com/KRR-Oxford/DeepOnto.git
```

This configuration allows the BERTMap pipeline to run without errors.

---

### 🙏 Suggestion

- Please consider pinning `transformers<5.0` and a compatible version of `accelerate` in the documentation or `requirements.txt`.
- Alternatively, it would be helpful if `deeponto` were updated to support the new `transformers` 5.x API.

Thank you for developing this excellent ontology alignment tool!

**Comment by akikuno** [comment]
The version of transformers I was used was incorrect, so I will check and resend the issue.
